name: Deploy NX Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection"
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.SERVERIP }} exit
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}


      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/clemens/nx-monorepo
            git pull
            npm install
            npm run build
            pm2 restart ecosystem.config.js
